apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeter-server
    version: v1
  name: greeter-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter-server
      version: v1
  template:
    metadata:
      labels:
        app: greeter-server
        version: v1
    spec:
      containers:
        - image: greeter-server:latest
          name: greeter-server
          ports:
            - containerPort: 50051
              protocol: TCP
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0